# Generated by Django 5.1.4 on 2026-01-25 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter apenas dígitos, entre 10 e 15 caracteres (ex: 11999998888).', regex='^\\d{10,15}$')]),
        ),
    ]
