# Generated by Django 5.1.4 on 2026-01-25 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter apenas dígitos (10 a 15 caracteres).', regex='^\\d{10,15}$')]),
        ),
    ]
