# Generated by Django 5.1.4 on 2026-01-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoPrestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(help_text='Nome do ícone (ex: bi-code-slash)', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('analise', 'Em Análise'), ('enviado', 'Orçamento Enviado'), ('finalizado', 'Finalizado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
