# Generated by Django 5.1.4 on 2026-01-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_servicoprestado_orcamento_status_orcamento_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='portfolio/')),
                ('tecnologias', models.CharField(help_text='Ex: Python, Django, Docker', max_length=200)),
                ('data_conclusao', models.DateField()),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_conclusao'],
            },
        ),
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='servicoprestado',
            options={'verbose_name': 'Serviço Prestado', 'verbose_name_plural': 'Serviços Prestados'},
        ),
        migrations.AlterField(
            model_name='servicoprestado',
            name='icone',
            field=models.CharField(help_text='Ex: bi-cpu, bi-code-slash, bi-diagram-3', max_length=50),
        ),
    ]
